### ISSUE TITLE
Initial issue: getting the basics working

### ISSUE THREAD

**Issue by gavstapes** [StapleIT/flask_inertia_svelte#1]
Using flask-inertia and the inertia.js svelte adapter.
Followed Inertia.js svelte setup from website, flask-inertia tutorial (uses Vue3 as frontend), pingcrm-flask, pingcrm-svelte
Using svelte template as basis for svelte set up.  Put the svelte files in static/svelte in the flask project folder structure
Svelte uses Rollup to bundle the app to javascript.
Performed npm install and npm run dev when in the svelte folder. Therefore bundles end up in static/svelte/public/ folder

In main.js pointed to './src/pages/${name}.svelte'  for the dynamic import of the svelte pages.  This is how it's done in the vue implementation ... assume the intent is for this to be bundled appropriately by the bundler because this relative location is not available to the bundle.js file.

```
createInertiaApp({
    resolve: async (name) => {
        return await import(`./src/pages/${name}.svelte`);
    },
    setup({ el, App, props }) {
        new App({ target: el, props });
    },
});
```

When running flask app, all runs without error.  BUT, when accessing the webpage at localhost:5000, the page is blank
Looking at the dev tools console, there is a 404 not found error when trying to import Index.svelte

Tried pointing to '../../src/pages/${name}.svelte' to get out of bundle's folder to the src pages folder, but then it gives Mimetype error because the raw svelte file is not javascript ... this makes sense.

So it seems that the problem is that the dynamic import pages (essential for Inertia.js to work) are not being included in the bundle as expected.

Read something suggesting that Rollup does not natively deal with dynamic imports.  Installed rollup plugin "@rollup/plugin-dynamic-import-vars"
This failed during bundling with 

> [!] (plugin rollup-plugin-dynamic-import-variables) SyntaxError: Unexpected token (2:9)
> node_modules/axios/package.json (2:9)
> SyntaxError: Unexpected token (2:9)
>     at Parser.pp$4.raise (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:19636:13)
>     at Parser.pp$9.unexpected (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:16932:8)
>     at Parser.pp$9.semicolon (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:16909:66)
>     at Parser.pp$8.parseExpressionStatement (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:17392:8)
>     at Parser.pp$8.parseStatement (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:17125:24)
>     at Parser.pp$8.parseBlock (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:17408:21)
>     at Parser.pp$8.parseStatement (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:17090:36)
>     at Parser.pp$8.parseTopLevel (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:16989:21)
>     at Parser.parse (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:16762:15)
>     at Function.parse (/home/gavin/PythonProjects/flask_inertia_svelte/static/svelte/node_modules/rollup/dist/shared/rollup.js:16812:35)_

Next tried composing the dynamic import code exactly as per the example in the plugin's documentation.

```
function importPages(page) {
    return import(`./src/pages/${page}.svelte`);
}

createInertiaApp({
    resolve: importPages(name),
    setup({ el, App, props }) {
        new App({ target: el, props });
    },
});
```
This didn't change the output or the error log.

Next tried introducing babel plugin to rollup.config and a .babelrc file with "@babel/plugin-syntax-dynamic-import".  And in main.js used

```
createInertiaApp({
    resolve: (name) => import(`./pages/${name}.svelte`),
    setup({ el, App, props }) {
        new App({ target: el, props });
    },
});
```

This produced a 404 error when trying to find static/svelte/public/build/pages/Index.svelte.  This implies that it has not dynamically imported the pages during the build, rather leaving the code as is and thus trying to find it in a path relative to the build folder. In the bundle.js file, the code is unchanged by the build process...

```
createInertiaApp({
      resolve: name => import(`./pages/${name}.svelte`),

      setup({
        el,
        App,
        props
      }) {
        new App({
          target: el,
          props
        });
      }

    });
```

**Comment by gavstapes** [comment]
Tried to use Reinink/svelete's explicit approach of pre-importing all the svelte pages.

```
import Index from "./pages/Index.svelte";
createInertiaApp({
    resolve: (name) => {
        let pages = { Index };
        return pages[name];
    },
    setup({ el, App, props }) {
        new App({ target: el, props });
    },
});
```

This produced different errors:

<App> was created with unknown prop 'initialComponent'
<App> was created with unknown prop 'onHeadUpdate'
<Render> was created without expected prop 'component'
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED  bundle.js

**Comment by gavstapes** [comment]
Need to prove that all this is in fact due to Rollup.  Will use the svelte webpack template as a basis for the svelte part of the project and see if that improves things

**Comment by gavstapes** [comment]
Tried with Webpack and it worked much better, but seemed to create many files and when running in dev, kept re-running over and over again?????
